### ISSUE TITLE
Freshmeat error IndexError: list index out of range

### ISSUE THREAD

**Issue by Nieczysty** [Kowlin/Sentinel#31]
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/bot/cogs/CogManager/cogs/freshmeat/freshmeat.py", line 61, in freshmeat
    await menu(
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/utils/menus.py", line 59, in menu
    if not isinstance(pages[0], (discord.Embed, str)):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range

**Comment by Jackenmen** [comment]
Thanks for the report, should be fixed in the latest commit.
