### ISSUE TITLE
[SentryIO] Cog doesn't seem to catch unhandled exceptions in a task

### ISSUE THREAD

**Issue by Jackenmen** [Kowlin/Sentinel#34]
Code:
````
[p]eval ```py
async def blah():
    raise RuntimeError(":(")

asyncio.create_task(blah())
```
````
produces log entry:
```
[2021-02-19 03:36:36] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "<string>", line 4, in blah
RuntimeError: :(
```
but SentryIO cog doesn't seem to send it to Sentry.

**Comment by MrNinjajuice** [comment]
[2021-02-19 03:36:36] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "<string>", line 4, in blah
RuntimeError: :(
